FROM ubuntu:20.04
#ENV http_proxy='<ADD_PROXY_SERVER>'
#ENV https_proxy='<ADD_PROXY_SERVER>'
# Necessary for tzdata
ENV DEBIAN_FRONTEND=noninteractive
ARG TZ_ARG=UTC
ENV TZ=${TZ_ARG}
# Add i386 support for support for Pin
RUN dpkg --add-architecture i386
RUN apt-get update && apt-get install -y \
    python \
    screen \
    tmux \
    binutils \
    libc6:i386 \
    libncurses5:i386 \
    libstdc++6:i386 \
 && rm -rf /var/lib/apt/lists/*
# For building Sniper
RUN apt-get update && apt-get install -y \
    automake \
    build-essential \
    curl \
    wget \
    libboost-dev \
    libsqlite3-dev \
    zlib1g-dev \
    libbz2-dev \
 && rm -rf /var/lib/apt/lists/*
# For building RISC-V Tools
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    autotools-dev \
    bc \
    bison \
    curl \
    device-tree-compiler \
    flex \
    gawk \
    gperf \
    libexpat-dev \
    libgmp-dev \
    libmpc-dev \
    libmpfr-dev \
    libtool \
    libusb-1.0-0-dev \
    patchutils \
    pkg-config \
    texinfo \
    zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*
# Helper utilities
RUN apt-get update && apt-get install -y \
    gdb \
    gfortran \
    git \
    g++-9 \
    vim \
 && rm -rf /var/lib/apt/lists/*

# Pin 3.15 requires the command "systemd-detect-virt" which is part of systemd
RUN apt-get update && apt-get install -y \
    systemd \
 && rm -rf /var/lib/apt/lists/*


# PARSEC
RUN apt-get update && apt-get install -y \
    xsltproc \
    gettext \
    libx11-dev \
    libxext-dev \
    libxt-dev \
    libxmu-dev \
    libxi-dev \
 && rm -rf /var/lib/apt/lists/*


# simulationcontrol
RUN apt-get update && apt-get install -y \
    python3-pip \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir matplotlib==3.5.2 seaborn diskcache tabulate

# video creation
RUN apt-get update && apt-get install -y \
    ffmpeg \
 && rm -rf /var/lib/apt/lists/*
