/*
 * Copyright 2002-2019 Intel Corporation.
 * 
 * This software and the related documents are Intel copyrighted materials, and your
 * use of them is governed by the express license under which they were provided to
 * you ("License"). Unless the License provides otherwise, you may not use, modify,
 * copy, publish, distribute, disclose or transmit this software or the related
 * documents without Intel's prior written permission.
 * 
 * This software and the related documents are provided as is, with no express or
 * implied warranties, other than those that are expressly stated in the License.
 */


/*************************************************************
 *
 *                  DO NOT EDIT THIS FILE!
 *
 * THIS FILE IS AUTOGENERATED BY THE PIN BUILD SYSTEM
 *
 *************************************************************/

#ifndef PIN_VERSION_H
#define PIN_VERSION_H


/*! @ingroup MISC
 * The Pin major version number.
 */
#define PIN_PRODUCT_VERSION_MAJOR 3

/*! @ingroup MISC
 * The Pin minor version number.
 */
#define PIN_PRODUCT_VERSION_MINOR 15

/*! @ingroup MISC
 * The Pin kit build number. This is unique for every Pin kit.
 */
#define PIN_BUILD_NUMBER 98253

/*! @ingroup MISC
 * The git hash for this Pin build. This is unique for every Pin kit.
 */
#define PIN_COMMIT_HASH "b56e429b1"

#endif // PIN_VERSION_H
